---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, message = FALSE,
                      fig.path="figures/",
                      fig.width=8, fig.height=6,
                      fig.show='hold', fig.align='center')

options(width=100)
```

```{r}
mineral <- read.table("data/mineral.DAT")

colnames(mineral) <- c("domradius", "radius", "domhumerus", "humerus", "domulna", "ulna")
```

```{r}
means <- colMeans(mineral)
n <- nrow(mineral)
s <- apply(mineral, 2, sd)
t <- qt(1 - (0.05 / 2), n - 1)
mult <- t * s / sqrt(n)

lower_ci <- means - mult
upper_ci <- means + mult

data.frame(lower_ci, upper_ci)

t_bonf <- qt(1 - (0.05 / (2 * 6)), n - 1)
mult_bonf <- t_bonf * s / sqrt(n)

lower_ci_bonf <- means - mult_bonf
upper_ci_bonf <- means + mult_bonf

data.frame(lower_ci_bonf, upper_ci_bonf)

n_vars <- ncol(mineral)

F_val <- qf(0.95, n_vars, n - n_vars)
mult_simul <- sqrt(n_vars * (n - 1) / (n - n_vars) * F_val) * s / sqrt(n)

lower_ci_simul <- means - mult_simul
upper_ci_simul <- means + mult_simul

data.frame(lower_ci_simul, upper_ci_simul)
```

