---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, message = FALSE,
                      fig.path="figures/",
                      fig.width=8, fig.height=6,
                      fig.show='hold', fig.align='center')

options(width=100)
```

```{r}
nutrient <- read.table("data/nutrient.txt")

colnames(nutrient) <- c("ID", "Calcium", "Iron", "Protein", "A", "C")

# Assign the unique IDs to the row names then remove the ID column
rownames(nutrient) <- nutrient$ID
nutrient <- nutrient[, -1]
```

```{r}
means <- colMeans(nutrient)

recommended <- c(1000, 15, 60, 800, 75)

diffs <- means - recommended

nutrient_cov <- cov(nutrient)

nutrient_cov_inv <- solve(nutrient_cov)

n <- nrow(nutrient)
T_2 <- n * t(diffs) %*% nutrient_cov_inv %*% diffs

T_2

p <- ncol(nutrient)
(n - p) / (p * (n - 1)) * T_2
```

```{r}
s <- apply(nutrient, 2, sd)
t_bonf <- qt(1 - 0.05 / (2 * p), n - 1)
mult_bonf <- t_bonf * s / sqrt(n)

lower_ci_bonf <- means - mult_bonf
upper_ci_bonf <- means + mult_bonf

data.frame(lower_ci_bonf, upper_ci_bonf)
```

